#!/usr/bin/env python3

import sys

import jmc

if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("Usage: {} model.jmm < input.txt".format(sys.argv[0]))
    model = jmc.Jmc.load(sys.argv[1])
    # TODO: implement an efficient best n algorithm
