#!/usr/bin/env python3

import sys

import subcli
import jmc

subcommand = subcli.Subcommand()

@subcommand("best")
def best(argv):
    if len(argv) != 4:
        sys.exit("Usage: {} {} NUM model.jmc < input.txt".format(*argv[:2]))
    model = jmc.Jmc.load(argv[3])
    in_lines = (model.decorate(line.rstrip("\n")) for line in sys.stdin)
    for line in model.best(int(argv[2]), in_lines):
        print(line)

@subcommand("loss")
def loss(argv):
    if len(argv) != 3:
        sys.exit("Usage: {} {} model.jmc < input.txt".format(*argv[:2]))
    model = jmc.Jmc.load(argv[2])
    for line in sys.stdin:
        print(model.loss(model.decorate(line.rstrip("\n"))))

subcommand.run(sys.argv, sys.exit)
