#!/usr/bin/env python3

##
# Copyright (C) 2022 Tomas "trosos" Tintera
#
# Permission to use, copy, modify, and/or distribute this
# software for any purpose with or without fee is hereby
# granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS
# ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
# WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH
# THE USE OR PERFORMANCE OF THIS SOFTWARE.
##

import sys
import pickle
import math

import jmc

def single_loss(model, gram, branch):
    return -math.log(
        sum(model.lambdas[len(gram) + branch:])/model.vocab_size
        + sum(
            model.lambdas[len(gram) - k - 1]*model.single_prob(gram[k:])
            for k in range(len(gram))
        )
    )

def get_descriptor(model):
    return {
        "stats": [{
            gram.replace("\N{LOWER ONE EIGHTH BLOCK}", "\n"):
                single_loss(model, gram, branch)
            for k, counts in enumerate(model.counts, -model.order)
                if branch + k < 0
            for gram in counts
        } for branch in range(model.order)],
    }

if __name__ == "__main__":
    if len(sys.argv) != 1:
        sys.exit("Usage: {} < model.pkl > model.jmc".format(sys.argv[0]))
    descriptor = get_descriptor(pickle.load(sys.stdin.buffer))
    jmc_model = jmc.Jmc(**descriptor)
    jmc_model.dump(sys.stdout.buffer)
